language: objective-c

env:
 global:
  - EnableNuGetPackageRestore=true 
 matrix:
  - MONO_VER="3.1.12"

before_install:
 - wget "http://download.mono-project.com/archive/3.2.1/macos-10-x86/MonoFramework-MDK-3.2.1_1.macos10.xamarin.x86.pkg"
 - sudo installer -pkg "MonoFramework-MDK-3.2.1_1.macos10.xamarin.x86.pkg" -target /

script:
 -  xbuild xbuild.proj
